### ISSUE TITLE
TODO product backlog bearbeiten

### ISSUE THREAD

**Issue by juliakt** [sweIhm-ws2018-19/skillproject-fr-22#18]
- [x]  Erstellen Sie einen Product Backlog für das gesamte Praktikumsprojekt. Den Product Backlog erstellen Sie unter Verwendung von Github Issues.  

- [x]  Erstellen Sie ein 'Project' in Github und clicken Sie auf 'add column'. Diese Spalte nennen Sie 'Product Backlog'. Weitere Spalten in Ihrem Projekt sind 'Ready' (ready to be worked on), 'In Progress' (currently worked on) und  'Done'.

- [x]  Für jede User Story im Product Backlog erstellen Sie ein Github Issue. 
Tipps wie man gute User Stories schreibt: http://www.romanpichler.com/blog/10-tips-writing-good-user-stories/

- [x]  Jede User Story hat einen Titel, eine Story, eine aussagekräftige Beschreibung und Akzeptanzkriterien. Gerne können auch Diagramme oder Abbildungen Teil der Beschreibung der User Story sein.

- [x]  Fügen Sie die Github Issues zu Ihrem Projekt hinzu: https://help.github.com/articles/adding-issues-and-pull-requests-to-a-project-board/

**Comment by juliakt** [comment]
ready heißt bei uns to do, ist schon so vordefiniert und neue issues kommen da automatisch rein, das ist schon gut so wie es ist find ich
